### ISSUE TITLE
ERROR WHEN USE PORT 4045

### ISSUE THREAD

**Issue by zidane-sc** [imamfzn/jcc-phase3-week2#3]
### OS
Windows 11 Home Single Language

### CHROME VERSION
Version 97.0.4692.71 (Official Build) (64-bit)

### PROBLEM
Can't access http://localhost:4045 (ERR_UNSAFE_PORT)

## IMAGE
![ERRORPORT4045](https://user-images.githubusercontent.com/67301786/148731065-3d80193b-b007-4b84-8e54-2509bddae1b4.png)

### WHAT HAVE I TRIED
add --explicitly-allowed-ports=4045 to chrome properties target
Link: [thegeekpage](https://thegeekpage.com/err-unsafe-port/)

**Comment by imamfzn** [comment]
Halo @zidane-sc thanks udah nge submit issue disini. Bisa tolong di screenshoot hasil dari `docker ps` di sini ? Thanks !

**Comment by imamfzn** [comment]
Sorry, i don't know that `4045` is kind of unsafe port. Thank you for your report, i already changed the requirement on https://github.com/imamfzn/jcc-phase3-week2/pull/4. Please check the update [here](https://github.com/imamfzn/jcc-phase3-week2/blob/master/day-1/tasks.md#running-a-simple-express-application).

You can use any port actualy besides the exposed port on dockerfile :).

Please tell your friend about this issue :)

Thanks @zidane-sc

**Comment by zidane-sc** [comment]
Thanks sir @imamfzn for your fast response

I will tell my friend

And Thank you for the information
